version: '3.8'  
  
services:  
  fastapi:  
    build: ./backend  
    ports:  
      - "8000:8000"  
      - "2222:2222"  
    volumes:  
      - ./honeypot-logs:/app/logs  
    depends_on:  
      - pentbox  
  
  pentbox:  
    build: ./pentbox-honeypot  
    ports:  
      - "23:23"  
    volumes:  
      - ./honeypot-logs:/honeypot-logs  
    privileged: true  
  
networks:  
  leakguard-net:  
    driver: bridge 
